---
- name: begin common
  debug:
    msg: Provision basic system configuration
  tags: always

- name: setup repositiories
  template:
    src: etc/apt/sources.list.j2
    dest: /etc/apt/sources.list
    owner: root
    group: root
    mode: 0644

- name: configure timezone
  template:
    src: etc/timezone.j2
    dest: /etc/timezone
    owner: root
    group: root
    mode: 0644
  notify:
    - update timezone

- name: configure locales
  template:
    src: etc/locale.gen.j2
    dest: /etc/locale.gen
    owner: root
    group: root
    mode: 0644
  notify:
    - generate locales

- name: configure default locale
  template:
    src: etc/locale.j2
    dest: /etc/default/locale
    owner: root
    group: root
    mode: 0644
  notify:
    - update locales

- name: link supported locales
  file:
    src: /etc/locale.gen
    dest: '{{ locale_gen_path }}'
    force: yes
    state: link
  when: locale_gen_path != '/etc/locale.gen'

- meta: flush_handlers
