---
- name: cleanup filesystem
  shell: rm -rfv {{ item }}
  args:
    executable: /bin/bash
    warn: no
  environment:
    BASHOPTS: extglob
  with_items:
    - /var/cache/apt/archives/!(partial)
    - /var/cache/apt/archives/partial/*
    - /var/lib/apt/lists/!(partial)
    - /var/lib/apt/lists/partial/*
    - /var/cache/debconf/*-old
    - /usr/share/locale/??
    - /usr/share/locale/??@*
    - /usr/share/locale/??_*
    - /usr/share/locale/???
    - /usr/share/man/??
    - /usr/share/man/??@*
    - /usr/share/man/??_*
    - /var/cache/man/??
    - /var/cache/man/??@*
    - /var/cache/man/??_*
  register: cleanup_result
  changed_when: cleanup_result.stdout
