---
- name: check variables
  assert:
    that:
      - target_path is string and target_path|length
  tags:
    - always

- name: begin configure
  debug:
    msg: Configure directory {{ target_path|path_abspath }}

- name: install configurations
  copy:
    src: '{{ item }}'
    dest: '{{ target_path|path_abspath }}/{{ item }}'
    owner: root
    group: root
    mode: 0644
  with_items:
    - etc/hostname
    - etc/hosts
    - etc/resolv.conf

- name: setup repositiories
  template:
    src: sources.list.j2
    dest: '{{ target_path|path_abspath }}/etc/apt/sources.list'
    owner: root
    group: root
    mode: 0644

- name: remove devices
  shell: rm -rfv {{ target_path|path_abspath }}/dev/!(null)
  args:
    executable: /bin/bash
    warn: no
  environment:
    BASHOPTS: extglob
  register: result
  changed_when: result.stdout
