---
- hosts: all
  gather_facts: no
  connection: chroot

  tags:
    - provision

  vars:
    ansible_ssh_host: '{{ target_path|path_abspath }}'

  pre_tasks:
    - name: begin provision
      debug:
        msg: Chrooting into directory '{{ ansible_ssh_host }}'
      connection: local

  roles:
    - role: common
    - role: docker-image
